name: Docker Build and Push
on:
  push:
    branches:
      - staging

env:
  IMAGE_NAME: tunlyinaung/demoapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      
      - name: GET short SHA
        id: short-sha
        uses: benjlevesque/short-sha@v2.2
        with:
          length: 6

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./nginx-demo/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.short-sha.outputs.sha }}

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Update Deployment yaml
        id: update-deployment-image
        run: |
          yq e '.spec.template.spec.containers[0].image = "${{ env.IMAGE_NAME }}:${{ steps.short-sha.outputs.sha }}"' -i nginx-deployment.yaml
        working-directory: nginx-demo

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with: 
          token: ${{ secrets.AUTH_TOKEN }}
          commit-message: "update image tag"
          title:  "update deployment image tag"
          body: This PR is auto created by Github Actions
          branch: update-tag
          base: main
          branch-suffix: random
          delete-branch: true
          labels: |
            automated-pr

