name: Docker Build and Push
on:
  push:
    branches:
      - staging

env:
  IMAGE_NAME: tunlyinaung/demoapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      
      - name: GET short SHA
        id: short-sha
        uses: benjlevesque/short-sha@v2.2
        with:
          length: 6

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./nginx-demo/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.short-sha.outputs.sha }}

